#!/bin/bash
# $COMMAND is the command used to create the reverse ssh tunnel
SSH_PORT="22"
REMOTE_HOST="xx.xx.xx.xx"
USER_NAME="analytics"
REMOTE_PORT="3306"
LOCAL_PORT="3307"
COMMAND="ssh -p $SSH_PORT -f -N -L $LOCAL_PORT:127.0.0.1:$REMOTE_PORT $USER_NAME@$REMOTE_HOST"

# Is the tunnel up? Perform two tests:

# 1. Check for relevant process ($COMMAND)
pgrep -f -x "$COMMAND" > /dev/null 2>&1 || $COMMAND
# 2. Test tunnel by looking at "netstat" output on $REMOTE_HOST
ssh -p $SSH_PORT $USER_NAME@$REMOTE_HOST netstat -an | egrep "tcp.*:$REMOTE_PORT.*LISTEN" \
   > /dev/null 2>&1
if [ $? -ne 0 ] ; then
   pkill -f -x "$COMMAND"
   $COMMAND
fi
